spring:
  application:
    name: currency-exchange
  config:
    import: "optional:configserver:http://localhost:8888"

resilience4j:
  retry:
    instances:
      sample-api:
        maxRetryAttempts: 5
        waitDuration: 2s
        enableExponentialBackoff: true


