spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://Users/ashish/Desktop/Currency_Application/git-local-config-repository
eureka:
  instance:
    host: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8888
